### PR TITLE
Select first deal.

### PR DESCRIPTION
**Pull request by YuriGizra**
#2

### CODE REVIEW

**Comment by amitaibu** [comment]
Is this ready? I see the tests are failing in Shoov.

**Comment by YuriGizra** [comment]
@amitaibu, ready for review:
[gif](http://gfycat.com/GrouchyMarriedBoutu)

**Comment by amitaibu** [comment]
Thanks. Why is the `wait` needed here?

**Comment by YuriGizra** [comment]
for this gif.

**Comment by amitaibu** [comment]
Ok, please remove.

**Pull request merged**
